version: '4'

services:
  postgres:
    container_name: potyguara
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: potyguara
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: potyguara-cache
    image: redis
    ports: 
      - 6379:6379
    volumes: 
      - ./data/redis:/data